language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base
    - source /opt/qt58/bin/qt58-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - sudo make install # Does not write to /usr
  - find .
  - mkdir -p appdir
  - sudo mv ./usr appdir/ ; sudo chown -R $USER appdir/ # Workaround for non-functional make install
  - cd appdir ; find .
  - mkdir -p ./usr/share/applications/ # Workaround for missing desktop file in make install
  - cp ../*.desktop ./usr/share/applications/
  - cp ./usr/share/icons/hicolor/48x48/apps/*.png .
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -appimage 
  - curl --upload-file ./SocNetV*.AppImage https://transfer.sh/SocNetV-git.$(git rev-parse --short HEAD)-x86_64.AppImage
