language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base qt58charts-no-lgpl qt58svg 
    - source /opt/qt58/bin/qt58-env.sh

script:
  - qmake # default: all go to /usr/local
  - make -j4
  - sudo make install
  - find .
  - mkdir -p appdir/usr/
  - sudo mv /usr/local appdir/ ; sudo chown -R $USER .  # move all from /usr/local to appdir
  - find appdir/
    #- make INSTALL_ROOT=appdir install; find appdir/
  - cp appdir/usr/share/applications/socnetv.desktop ./appdir
  - cp appdir/usr/share/pixmaps/socnetv.png .  
  - find /opt/qt58/plugins
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
    # - ./linuxdeployqt*.AppImage /usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage appdir/usr/share/applications/*.desktop -appimage -extra-plugins=iconengines,imageformats

after_success:
   - ls -lsh  
    #- curl --upload-file ./Social*.AppImage https://transfer.sh/SocNetV-git.$(git rev-parse --short HEAD)-x86_64.AppImage
   - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
   - bash upload.sh Social*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
