
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

language: cpp

os:
  - linux
  - osx

sudo: require

dist: trusty

compiler:
  - clang 
  - gcc

matrix:
  include:
    - os: linux
      compiler: gcc
      env: FAILURES=true
    - os: osx
      compiler: clang
      env: FAILURES=true
  exclude:
    - os: osx
      compiler: gcc      
  allow_failures:
    - env: FAILURES=TRUE


before_install:
  # Info about OS
  - uname -a
  - chmod +x .travis_before_install.sh
  - ./.travis_before_install.sh


#  Install any dependencies required

install: 
  - chmod +x .travis_install.sh
  - ./.travis_install.sh

#  Run the build script

script:
  -  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x ./travis_build_linux.sh ; fi
  - '[ "$TRAVIS_OS_NAME" != linux ] || ./.travis_build_linux.sh'
  -  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then chmod +x ./travis_build_macos.sh ; fi  
  - '[ "$TRAVIS_OS_NAME" != osx ] || ./.travis_build_macos.sh'
  # - qmake # default: all go to /usr
  # - make -j4
  # - find .
  # - make INSTALL_ROOT=appdir install; find appdir/
  # - cp appdir/usr/share/applications/socnetv.desktop ./appdir
  # - cp appdir/usr/share/pixmaps/socnetv.png .  
  # - find /opt/qt58/plugins
  # - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  # - chmod a+x linuxdeployqt*.AppImage
  # - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  #   # - ./linuxdeployqt*.AppImage /usr/share/applications/*.desktop -bundle-non-qt-libs
  # - ./linuxdeployqt*.AppImage appdir/usr/share/applications/*.desktop -appimage -extra-plugins=iconengines,imageformats

after_success:
   - ls -lsh  
    #- curl --upload-file ./Social*.AppImage https://transfer.sh/SocNetV-git.$(git rev-parse --short HEAD)-x86_64.AppImage
   - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
   - bash upload.sh Social*.AppImage*

